-- Keep a log of any SQL queries you execute as you solve the mystery.
select * from crime_scene_reports;
select * from crime_scene_reports where year = 2020 and month = July;
select * from crime_scene_reports where year = 2020 and month = 7;
select description from crime_scene_reports where year = 2020 and month = 7 and day = 28;
select description from crime_scene_reports where year = 2020 and month = 7 and day = 28;
select * from people;
select * from interviews where transcript like "%courthouse%";
select name, transcript from interviews where transcript like "%courthouse%" and year = 2020 and month = 7 and day = 28;
select * from people;
select year, hour, minute, activity, license_plate from courthouse_security_logs where year = 2020 and month = 7 and day = 28;
select year, hour, minute, activity, license_plate from courthouse_security_logs where year = 2020 and month = 7 and day = 2 and hour = 10 and minute < 15 and minute > 25;
select(select phone_number from people where license_plate in (select license_plate from courthouse_security_logs where year = 2020 and month = 7 and day = 28 and hour = 10 and minute > 15 and minute < 25));
select * from phone_calls;
select caller from phone_calls where duration > 60;
select name from people inner join phone_calls on people.phone_number=phone_calls.caller where year = 2020 and month = 7 and day = 28 and duration < 60;
select passport_number in passengers;
select passport_number from passengers;
select passport_number from passengers where passport_number in (select passport_number from people where name = "Roger" or name = "Evelyn" or name = "Ernest");
select passengers.passport_number from passengers inner join people on passengers.passport_number=people.passport_number where passengers.passport_number in (select passport_number from people where name = "Roger" or name = "Evelyn" or name = "Ernest"));
select reciever from phone_calls where duration > 60;
select * from bank_accounts;
select * from atm_transactions where year = 2020 and month = 7 and day = 28;
select * from atm_transactions where year = 2020 and month = 7 and day = 28 and atm_location = "Fifer Street";
select person_id from bank_accounts where account_number in(select account_number from atm_transactions where year = 2020 and month = 7 and day = 28 and atm_location = "Fifer Street");
select city from airports where id in (select destination_airport_id from flights where id = (select flight_id from passengers where passport_number = (select passport_number from people where name = "Ernest")));
select(select name from people where phone_number in (select receiver from phone_calls where year = 2020 and month = 7 and day = 28 and duration < 60));
select receiver from phone_calls where caller = "Ernest";
select receiver from phone_calls where caller = "(367) 555-5533";
select name from people where phone_number = (select receiver from phone_calls where caller = "(367) 555-5533");
select name from people where phone_number in (select receiver from phone_calls where caller = "(367) 555-5533");
select name from people where phone_number in (select receiver from phone_calls where caller = "(367) 555-5533" where year = 2020 and month = 7 and day = 28);
select name from people where phone_number in (select receiver from phone_calls where caller = "(367) 555-5533" and year = 2020 and month = 7 and day = 28 and duration < 60);
